require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
end

target 'App' do
  capacitor_pods
  # Add your Pods here

  # AdMob: @capacitor-community/admob v6.2.0'in consent modülü eski UMP API'sini
  # (UMPConsentInformation, sharedInstance vb.) kullanıyor. UMP 3.x bu sembolleri
  # yeniden adlandırdığı için derleme kırılıyor. Google-Mobile-Ads-SDK zaten plugin
  # tarafından 11.3.0'a sabit; biz de UMP'yi 2.x'te tutuyoruz.
  pod 'GoogleUserMessagingPlatform', '< 3.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
